### ISSUE TITLE
Virus in release?

### ISSUE THREAD

**Issue by rationalthinker1** [x1nixmzeng/xbox-iso-vfs#9]
Hello, I tried to download the latest release and it said that it had Script/Wacatac.B!ml trojan in the zip file.

**Comment by x1nixmzeng** [comment]
Hey, thanks for reporting this - Windows Defender now gives me the same error - the !ml tag means this is identified by machine learning and this is a false positive. I have no idea how to fix this unfortunately.

However, the zip file is just there for convenience - I suggest building this yourself from source

**Comment by x1nixmzeng** [comment]
@rationalthinker1 I am closing this issue as Windows Defender no longer flags the release zip file

For what it's worth, here are the results from virus total:

https://www.virustotal.com/gui/file/9657979bc437f0ef4e0dfd0722719fd42a43fd3690f91161cf5a275ba9871818
